# NUR-compatible entrypoint. Flake outputs are generated by blueprint in flake.nix.
{
  pkgs ? import <nixpkgs> { },
}:
let
  inherit (pkgs) lib;

  reservedPackageDirs = [
    "default"
    "formatter"
  ];

  packageDirs = lib.filterAttrs (
    name: type:
    type == "directory"
    && !(builtins.elem name reservedPackageDirs)
    && builtins.pathExists (./packages + "/${name}/default.nix")
  ) (builtins.readDir ./packages);

  packages = lib.mapAttrs (name: _: import (./packages + "/${name}") { inherit pkgs; }) packageDirs;
in
{
  lib = import ./lib { inherit pkgs; };
  nixosModules = {
    mihomo-warp = ./modules/nixos/mihomo-warp.nix;
    usque = ./modules/nixos/usque.nix;
  };
  overlays = import ./overlays;
}
// packages
