name: Build Packages

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.system }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            system: x86_64-linux
          - runner: ubuntu-24.04-arm
            system: aarch64-linux
          - runner: macos-latest
            system: aarch64-darwin
    steps:
      - uses: actions/checkout@v7
      - name: Set up Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-substituters = https://cache.bingyin.org
            extra-trusted-public-keys = cache.bingyin.org-1:PU5qCuJfhYPKSIRdOMCndVB6Dn9rRRIRVZAnG2uAPSI=
            access-tokens = github.com=${{ github.token }}
      - name: Build packages
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
          SYSTEM: ${{ matrix.system }}
        run: ./.github/ci/build_native_packages.py
