name: Lint

on:
  workflow_call:
    inputs:
      merged-repository:
        required: true
        type: string
      merged-sha:
        required: true
        type: string
      target-sha:
        required: true
        type: string

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  treefmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout trusted
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          ref: ${{ inputs.target-sha }}
          path: trusted
      - name: Checkout untrusted
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          repository: ${{ inputs.merged-repository }}
          ref: ${{ inputs.merged-sha }}
          path: untrusted
      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = true
            allow-import-from-derivation = false
            accept-flake-config = false
      - name: Check formatting
        run: |
          formatter=$(nix build \
            --no-link \
            --no-write-lock-file \
            --print-out-paths \
            "path:$GITHUB_WORKSPACE/trusted#formatter.x86_64-linux")
          "$formatter/bin/treefmt" --ci -C "$GITHUB_WORKSPACE/untrusted"

  parse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout untrusted
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          repository: ${{ inputs.merged-repository }}
          ref: ${{ inputs.merged-sha }}
          path: untrusted
      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = true
            allow-import-from-derivation = false
            accept-flake-config = false
      - name: Parse
        run: |
          while IFS= read -r -d '' file; do
            echo "parsing $file"
            nix-instantiate --parse "$file" >/dev/null
          done < <(find untrusted -type f -name '*.nix' -print0 | sort -z)
